name: BrainComp
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - asttokens=3.0.0
  - bctpy=0.6.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.3
  - cmasher=1.9.2
  - colorspacious=1.1.2
  - comm=0.2.3
  - contourpy=1.3.3
  - cycler=0.12.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - fonttools=4.60.0
  - freetype=2.14.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=6.30.1
  - ipython=9.5.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - joblib=1.5.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libdeflate<1.23
  - libedit=3.1.20250104
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - littleutils=0.2.4
  - llvm-openmp=21.1.0
  - lxml=6.0.1
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nibabel=5.3.2
  - nilearn=0.12.1
  - numpy=2.3.3
  - openjpeg=2.5.3
  - openssl=3.5.3
  - outdated=0.2.2
  - packaging=25.0
  - pandas=2.3.2
  - pandas-flavor=0.7.0
  - parso=0.8.5
  - patsy=1.0.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pingouin=0.5.5
  - pip=25.2
  - plink
  - pooch=1.8.2
  - platformdirs=4.4.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.4
  - pyvista=0.45.1
  - pyvistaqt=0.11.0
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pyzmq=27.1.0
  - qhull=2020.2
  - readline=8.2
  - requests=2.32.5
  - r-base=4.4.2
  - r-data.table
  - r-dplyr
  - r-ggplot2
  - r-lavaan
  - r-languageserver
  - r-psych
  - r-tibble
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - six=1.17.0
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - tabulate=0.9.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xarray=2025.9.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstandard=0.25.0
  - zstd=1.5.7
  - vtk
